global:
  scrape_interval: 5s # Scrape often for dev/learning (default is usually 1m)

scrape_configs:
  - job_name: 'go_app'
    static_configs:
      - targets: ['host.docker.internal:8080'] # <--- CRITICAL: Points to your host machine